testinfo:
      id: test_01_create_project        # 用例ID， 用于识别     string
      title: 创建项目                 # 用例标题，在报告中作为一级目录显示  必填 string
      port: 5000          # 请求的域名，可写死，也可写成模板关联host配置文件  选填（此处不填，每条用例必填） string
      address: # 请求地址 选填（此处不填，每条用例必填） string

# 前置条件，case之前需关联的接口
premise:

# 测试用例
test_case:
      # 第一条case，info可不填
    - test_name: 正常创建项目       # 必填，parameter为文件路径时
      http_type: http          # 请求协议
      request_type: post      # 请求类型
      parameter_type: raw     # 参数类型
      address: /v3/projects
      headers:                # 请求头
            Content-Type: application/json
            X-Auth-Token: ${token_id}$
      timeout: 20
      parameter:
        project:
          description: Automation_wuzs
          domain_id: default
          enabled: true
          is_domain: false
          name: ${project_name}$
      file: false
      check:             # 校验列表  list or dict
          - check_type: json # 校验类型 string   不校验时 datebase， expected_code, expected_request 均可不填
            datebase:
            expected_code: 200
            expected_request: {}
      relevance:  # 关联键


